version: '3.7'
services:
#  app:
#    build: .
#    ports:
#      - 8000:8000
  mongodb_container:
    image: docker.io/mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
